spring.application.name=erp
spring.datasource.url=jdbc:sqlserver://67.211.210.15:1433;databaseName=WarshaDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Info@2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=${PORT:8080}
# Maximum file size for a single file
spring.servlet.multipart.max-file-size=15MB
# Maximum request size (all files + form data)
spring.servlet.multipart.max-request-size=15MB
#ignoring auto naming columns

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

#spring.application.name=erp
#spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=erpV1.0.0-alpha;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=Info@2025
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
##ignoring auto naming columns
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

google.client.id=881242863381-rubnpv9csakd68e5hgt30bll7om5fbde.apps.googleusercontent.com
google.client.secret=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
google.refresh.token=1//03jntyRoqz7blCgYIARAAGAMSNwF-L9IriIAn6ZCZ1PZWL837dS51eN8FKkQfaZ14iPbSPGk7J54mNbDr1zzpZoWZB_zqRN77ZdU
google.drive.folder.id=1PCfi0vdmcArMoXKRjgNL4lPNq3WnnSkL
google.application.name=WarshaBackend
